//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string UPC { get{
           return serial_number.Trim();
        } set{
            serial_number = value;
        } }
        public string serial_number { get; set; }
        public string model_number { get; set; }
        public string manufacturer { get; set; }
        public string building_ID { get; set; }
        public Nullable<System.DateTime> surplus_date { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string description { get; set; }
        public Nullable<int> PO_number { get; set; }
        public Nullable<System.DateTime> checked_out { get; set; }
        public Nullable<System.DateTime> checked_in { get; set; }
        public Nullable<int> person_ID { get; set; }
        public string decal { get; set; }
    }
}
